### PR TITLE
Made a BMI Calculator

### PR DESCRIPTION
**Pull request by Vanshiii203**
Made a BMI Calculator using HTML,CSS and JavaScript
Fixes:  #23 
# Checklist:
- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
screenshot-1
screenshot-2

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You have added css loaders files too?

**Comment by Vanshiii203** [comment]
> You have added css loaders files too?

I did it by mistake. I have removed them. Sorry for that.

**Comment by Sulagna-Dutta-Roy** [comment]
@Vanshiii203 still showing css loaders folder here. kindly delete it

**Comment by Vanshiii203** [comment]
> @Vanshiii203 still showing css loaders folder here. kindly delete it

Deleted!
Screenshot (304)

**Comment by Sulagna-Dutta-Roy** [comment]
LGTM !!

**Review by siddhi-244 — APPROVED** [review]
Lgtm

**Pull request merged**
