### PR TITLE
#9 To-Do List 

### PR DESCRIPTION
**Pull request by vaibhavchaubey**
# Description

This is a simple To-Do List where users can add daily tasks.
In this, I have implemented **CRUD** Operation i.e. users can create, read, update and delete the items in the list

Fixes:  #9 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / [DEPLOYMENT LINK](https://vaibhavchaubey.github.io/todo-list-with-js/)
Pic_1

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
There is dice game too?

**Comment by vaibhavchaubey** [comment]
> There is dice game too?

Yes but for Dice-Game i have made separate PR

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please delete dice game files. It's overriding the two PRs. Tell me you pushed two prs from one branch right ???

**Comment by vaibhavchaubey** [comment]
> Please delete dice game files. It's overriding the two PRs. Tell me you pushed two prs from one branch right ???

No, i have made separate branches.
Ok i will delete the dice game file and then push the changes.

**Comment by vaibhavchaubey** [comment]
> Please delete dice game files. It's overriding the two PRs. Tell me you pushed two prs from one branch right ???

I have deleted the Dice-Game file please check it out

**Comment by Sulagna-Dutta-Roy** [comment]
Hey please open new pull request. It has conflicts

**Comment by vaibhavchaubey** [comment]
> Hey please open new pull request. It has conflicts

Ok i will open new pr.

**Pull request closed without merging**
