### PR TITLE
Added Random Password Generator.

### PR DESCRIPTION
**Pull request by AyushPathak3011**
Added the source code for the Random Password Generator website built using HTML, CSS, and Javascript.

Files added inside the folder:
- index.html
- styles.css
- main.js
- font
- assets

# Description

Created a website where users can generate a random and strong password. 

Fixes:  #27 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

## Random Password Generator
Screenshot 2022-08-04 at 10 57 05 PM

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Remove the extra commited files. You have added password generator and gradient in one pr. Make different prs

**Comment by AyushPathak3011** [comment]
@siddhi-244 I have reverted the extra commits, please review.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
There are some ds store files committed. Can you see to them ?

**Comment by AyushPathak3011** [comment]
> There are some ds store files committed. Can you see to them ?

I have removed the ds_store files now.

**Comment by Sulagna-Dutta-Roy** [comment]
@AyushPathak3011 please readme file with all the details.

**Comment by AyushPathak3011** [comment]
> @AyushPathak3011 please add readme file with all the details.

I have added the readme file.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Looks good to me. But can you try to remove that extra font file ?

**Comment by AyushPathak3011** [comment]
> Looks good to me. But can you try to remove that extra font file ?

Done.

**Review by siddhi-244 — APPROVED** [review]
LGTM🥳🥳🥳

**Pull request merged**
