### PR TITLE
Number Guessing Game

### PR DESCRIPTION
**Pull request by prjailani**
# Description
> Created a Number Guessing Game using Python
> Used Random Library for this project

Fixes: #282

## Type of change
- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update

# Checklist
- [x]  I have made this from my own
- [x]  I have taken help from some online recourses
- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (35)

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please add the PR template.check others Pull requests,don't delete the template

**Comment by prjailani** [comment]
> Please add the PR template.check others Pull requests,don't delete the template

Hi mam, Updated please see if it's ok, now. Thanks.

**Comment by Sulagna-Dutta-Roy** [comment]
This project is already exist. No proper Issue isn't opened for that

**Comment by prjailani** [comment]
Yes. But in Python it isn't available. That's why I made one.

**Comment by Sulagna-Dutta-Roy** [comment]
open a Issue for this. and mention then in the PR template

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]
Everything seems good. Kudos!

**Comment by prjailani** [comment]
Why still it's not merged?

**Comment by siddhi-244** [comment]
@Sulagna-Dutta-Roy please merge it!

**Comment by prjailani** [comment]
Fixed Issue No : #282

**Comment by Sulagna-Dutta-Roy** [comment]
Still you didn't write your Issue no in the PR template.look there I have added the Issue in the top.

**Pull request merged**
