### PR TITLE
added simon game

### PR DESCRIPTION
**Pull request by Harsh3363**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #7

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot (95)

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Please add readme file in the project @Harsh3363

**Comment by Harsh3363** [comment]
> Please add readme file in the project @Harsh3363

There is already a README.md file there

**Comment by Sulagna-Dutta-Roy** [comment]
I can't see the files.

**Comment by Harsh3363** [comment]
> I can't see the files. 

Okay I will make changes accordingly

**Pull request closed without merging**
