### PR TITLE
Simon game

### PR DESCRIPTION
**Pull request by Harsh3363**
# Description

This is webApp of 90's simon game start by pressing any key and enjoy the game.

Fixes:  #7 

## Type of change

Added the Simon game WebApp 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot (95)

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
I can't see the the readme screenshot Image.

**Comment by Harsh3363** [comment]
> I can't see the the readme screenshot Image.

done

**Comment by Harsh3363** [comment]
> > I can't see the the readme screenshot Image.
> 
> done
> 

@Sulagna-Dutta-Roy i have made the changes take a look if it's okay or not

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Harsh3363** [comment]
@Sulagna-Dutta-Roy is there any changes required to be done?

**Comment by Sulagna-Dutta-Roy** [comment]
LGTM !! @siddhi-244 will say any changes required or not

**Comment by Harsh3363** [comment]
> LGTM !! @siddhi-244 will say any changes required or not

okay

**Comment by Sulagna-Dutta-Roy** [comment]
@siddhi-244 please review this

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
