### PR TITLE
New Year counter web app

### PR DESCRIPTION
**Pull request by SD-13**
# Description

A web app that displays whether today is new year or not  or how many days remaining for next new years eve

Fixes:  #31 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
### On New Year's
Screenshot from 2022-08-08 11-21-00
### On other days (took the ss on the day I created this PR)
Screenshot from 2022-08-08 11-20-19

### CODE REVIEW

**Comment by SD-13** [comment]
@siddhi-244 @Sulagna-Dutta-Roy please take a pass. Thanks,

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Add this project under Python folder. Otherwise we will not consider.

**Comment by SD-13** [comment]
> Add this project under Python folder. Otherwise we will not consider.

Done. PTAL, Thanks

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
@siddhi-244 please approve it

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
