### PR TITLE
Chatbot using JavaScript

### PR DESCRIPTION
**Pull request by Arun9739**
# Description

- The chatbot has been created using the Javascript and JQuery.
- The chatbot is intercative means it asks questions to the user and takes answer.
- It asks question such as name, age, place etc.
- The bot is named on behalf of Webeginner projects.
- I have loaded the fonts and jquery through online liks.
- There are 3 files : .html, .css, .js which constitute the website.

Fixes:  #251 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

image

image

image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
change the css file name into style.css

**Comment by Arun9739** [comment]
@Sulagna-Dutta-Roy done the changes ma'am

**Review by siddhi-244 — APPROVED** [review]

**Comment by Arun9739** [comment]
@072arushi please review my pr

**Review by 072arushi — APPROVED** [review]

**Comment by Arun9739** [comment]
@Sulagna-Dutta-Roy please merge my pr

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
