### PR TITLE
youtube video downloader

### PR DESCRIPTION
**Pull request by srinjoy-26**
# Description

added youtube video downloader
Fixes:  #15 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/91176055/186477960-708b672f-76b2-47f2-8b92-64b3840b5562.mp4

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
What is the .idea folder?

**Comment by srinjoy-26** [comment]
> What is the .idea folder?

It's an IDE generated folder , since I used Pycharm of jetbrain's that's why it came

**Comment by srinjoy-26** [comment]
> Could you remove that?

Rehne dijiye na , kya bigad Raha h. Pyara sa file h 😅

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Please change the filename- Youtube Video Downloader.py

**Comment by srinjoy-26** [comment]
> Please change the filename- Youtube Video Downloader.py

Done

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
