### PR TITLE
Animated Carousel #178

### PR DESCRIPTION
**Pull request by Bhajneet-Singh-Bedi**
# Description

This is a minor webgineer project, explaining how to create an image slider using html, CSS and JavaScript. Jssor and Jquery JavaScript libraries and bootstrap CSS libraries have been used in this project.

Fixes:  #120

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:
- [x] I have taken help from some online resources 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

image
image
image
image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please follow the PR template and tick all the relevant checkboxes. Delete the .vscode file. Mention your Issue no also.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
please add your issue no the PR template. not the PR no

**Comment by Bhajneet-Singh-Bedi** [comment]
Please Check now

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please add readme

**Comment by Bhajneet-Singh-Bedi** [comment]
> Please add readme

Please check now

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
