### PR TITLE
add text-editor

### PR DESCRIPTION
**Pull request by Rishikavishnoi**
Adding a Text Editor web app using HTML, CSS, javascript, and bootstrap.

Fixes:  #52 

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
Screenshot 2022-08-06 003423

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Kindly add readme file with all the details.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please add one readme file with all the details.

**Comment by Rishikavishnoi** [comment]
done

**Review by siddhi-244 — APPROVED** [review]
LGTM🥳🥳

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
