### PR TITLE
TicTacToe

### PR DESCRIPTION
**Pull request by harshitjain156**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #6  

## Adding source code.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x]  My changes generate no new warnings

pic1
pic2

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add details in the readme file and add deployed Image. Also write about the python libraries that you used

**Comment by Sulagna-Dutta-Roy** [comment]
Tick all the appropriate checkboxes that relevant to the PR @harshitjain156

**Comment by Sulagna-Dutta-Roy** [comment]
kindly add your pic1,pic2 images in the readme file only. Otherwise delete it

**Comment by harshitjain156** [comment]
> kindly add your pic1,pic2 images in the readme file only. Otherwise delete it. Also tick all the checkboxes that relevant to the PR correctly.

Done. Please check.

**Comment by harshitjain156** [comment]
please check.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
