### PR TITLE
Number guessing game

### PR DESCRIPTION
**Pull request by Koustavjr**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #68 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Koustavjr** [comment]
@Sulagna-Dutta-Roy can u please check my pr

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please add a readme with details and ss

**Comment by Koustavjr** [comment]
> Please add a readme with details and ss

OK sure

**Comment by Koustavjr** [comment]
@siddhi-244 I have added the readme can u please check it.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
