### PR TITLE
Exploratory Data analysis (Spotify)

### PR DESCRIPTION
**Pull request by Labheshm11**
# Exploratory Data analysis (Spotify dataset)

issue no. #160 

## Description
This is a eda that makes us understand the basic fundamentals in the Spotify dataset

### Technologies
Python-(pandas,numpy,matplotlib,Kaggle(dataset)

Checklist:
[ ✅ ] I have made this on my own
[ ✅ ] I have taken help from some online resources
[ ✅ ] My code follows the style guidelines of this project
[ ✅ ] I have performed a self-review of my own code
[ ✅ ] I have commented on my code, particularly in hard-to-understand areas
[ ✅ ] I have made corresponding changes to the documentation
[ ✅ ] My changes generate no new warnings

Screenshot (169)
Screenshot (170)
Screenshot (171)

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Mention your Issue no in the PR template.

**Comment by Labheshm11** [comment]
Only I have to edit the template
No need to send another pr?

**Comment by Sulagna-Dutta-Roy** [comment]
LGTM !!!

**Comment by Labheshm11** [comment]
@siddhi-244  plz review the pr

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
