### PR TITLE
Character counter

### PR DESCRIPTION
**Pull request by Shaba1406**
# Description

- This is the Real-time character counter which reads the number of character preset in a string.
- This Project is made using HTML,CSS and JavaScript.
-  you can easily get the no. of character in a long sentences or paragraph.

Fixes: #255

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Real-time Charater Counter - Google Chrome 07-09-2022 22_27_05

### CODE REVIEW

**Comment by Shaba1406** [comment]
@Sulagna-Dutta-Roy @072arushi @siddhi-244 Kindly check my PR

**Review by Sulagna-Dutta-Roy — COMMENTED** [review]
please do the required changes

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Delete all the binary files that not needed. Delete the settings .vscode file not needed. Readme.md folder not needed delete it. Two readme files here please check it

**Comment by Shaba1406** [comment]
Done with the changes , What else i have to do ? @Sulagna-Dutta-Roy

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]
Good work! Keep it up!!

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
