### PR TITLE
Online Notepad added

### PR DESCRIPTION
**Pull request by iamrahul8**
# Description
A basic realtime notepad, made with HTML, CSS and Javascript.
This Notepad is a simple responsive design that contrasts the body backdrop with a single container.
This can be used to make notes about things read online.

Fixes (issue no.) :  #3

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

 [Deployment link](https://iamrahul8.github.io/Online-Notepad/)
 
 
preview

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
It would be great if you can add screenshot of your working website in the readme.

**Comment by iamrahul8** [comment]
> It would be great if you can add screenshot of your working website in the readme.

Done Ma'am , please do check ✌

**Review by siddhi-244 — APPROVED** [review]
Looks good to me🥳

**Comment by siddhi-244** [comment]
Why are you adding online calculator in same pr?

**Comment by siddhi-244** [comment]
You have to make different prs!

**Comment by iamrahul8** [comment]
> Why are you adding online calculator in same pr?

Sorry for mistake , I have removed the file ,

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
