### PR TITLE
Added Rock-Paper-Scissor game using python

### PR DESCRIPTION
**Pull request by SSHSRN**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #42

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resources 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
#42 Issue I didn't assigned you till now because you didn't replied to the mentor.

**Comment by Sulagna-Dutta-Roy** [comment]
Please make separate PRs we already told you, Also as per the Instructions please don't make any PR until you assigned

**Comment by SSHSRN** [comment]
I have now updated the branch as well as the pull request. It now has only the game of Rock-Paper-Scissor.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add screenshot in readme

**Comment by SSHSRN** [comment]
Yup, updated it now.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please filename change into Rock-Paper-Scissor.py

**Comment by SSHSRN** [comment]
I have renamed it now! 
@Sulagna-Dutta-Roy Kindly check.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
