### PR TITLE
Tribute Page project

### PR DESCRIPTION
**Pull request by anshulsoni4**
# Description

I made this tribute page with basic HTML/CSS which is fully responsive for all devices, a tribute to the great man Elon Musk!

Fixes:  #122 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
ss of project

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
.vscode file isn't needed here. kindly delete it.
Also add one Readme.md file here

**Comment by Sulagna-Dutta-Roy** [comment]
I can't see any readme file here. kindly go through other projects and add readme

**Comment by anshulsoni4** [comment]
added readme and removed vs code file 
pls review 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Reusable

**Comment by anshulsoni4** [comment]
@siddhi-244 PLS REVIEW THIS

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add more information in the readme

**Comment by anshulsoni4** [comment]
@siddhi-244 check now

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
The js file is empty right? So we won't need it!

**Comment by anshulsoni4** [comment]
> The js file is empty right? So we won't need it!

yes we don't need it

**Comment by siddhi-244** [comment]
> > The js file is empty right? So we won't need it!
> 
> yes we don't need it

Then remove it

**Comment by anshulsoni4** [comment]
> > > The js file is empty right? So we won't need it!
> > 
> > 
> > yes we don't need it
> 
> Then remove it

check now :)

**Comment by siddhi-244** [comment]
It's still there

**Comment by anshulsoni4** [comment]
> It's still there

Done ma'am

**Comment by anshulsoni4** [comment]
> > It's still there
> 
> Done ma'am

@siddhi-244 ??

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Comment by anshulsoni4** [comment]
when will you merge this ?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Pull request merged**
