### PR TITLE
Created Dynamic Table project

### PR DESCRIPTION
**Pull request by ShrutiMishra-2002**
# Description

- Dynamic Table:- Helps you to add the registration or any information dynamically in a structured table.
- Tech Stack used : HTML5, CSS3, JS.
Fixes:  #157 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
regssoc

### CODE REVIEW

**Comment by ShrutiMishra-2002** [comment]
@siddhi-244 Please review my pr

**Comment by Sulagna-Dutta-Roy** [comment]
Wait for some time. She'll review it

**Comment by Sulagna-Dutta-Roy** [comment]
Wait for some time. She'll review it

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please add readme file here.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Please add readme

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by ShrutiMishra-2002** [comment]
@Sulagna-Dutta-Roy  @siddhi-244 changes have been made. Kindly review it again.

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
