### PR TITLE
Online Calculator

### PR DESCRIPTION
**Pull request by iamrahul8**
# Description

This Online Calculator performs arithmetic operations on numbers. It can do addition, subtraction, multiplication, and division and more...

Fixes:  #20 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT [LINK](https://iamrahul8.github.io/Calculator/)
image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Kindly add online calculator files delete the other ones. Also update the readme with details

**Comment by iamrahul8** [comment]
> Kindly add online calculator files delete the other ones. Also update the readme with details

All files has been added 
- this PR has fetched my initial commits due to branch override
- But calc branch is clear to merge
- [Check this](https://github.com/iamrahul8/Webeginner-projects/tree/calc/Online%20Calculator)

**Comment by Sulagna-Dutta-Roy** [comment]
kindly make separate PRs. It is showing two PRs in one branch. Otherwise It will not accepted.

**Comment by Sulagna-Dutta-Roy** [comment]
@siddhi-244 please review it.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
There are online notepad files too. Make different prs for both

**Comment by iamrahul8** [comment]
https://github.com/Sulagna-Dutta-Roy/Webeginner-projects/pull/70

Please merge it 
Branch is clear ( no conflict present now)

**Comment by iamrahul8** [comment]
@siddhi-244

**Pull request closed without merging**
