### PR TITLE
Text editor

### PR DESCRIPTION
**Pull request by Avik-creator**
# Description

It is a text editor made by using Python.

Fixes:  #35 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2022-03-07 at 21 25 24

Screenshot 2022-03-07 at 21 09 59

### CODE REVIEW

**Comment by Avik-creator** [comment]
@siddhi-244 @Sulagna-Dutta-Roy Please check and assign

**Comment by siddhi-244** [comment]
I think we have this @Sulagna-Dutta-Roy

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Can uh add working ss in readme?

**Comment by Avik-creator** [comment]
@siddhi-244 I guess there is ss in readme.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Can you please change the file name into 'Text Editor.py' ?

**Comment by Avik-creator** [comment]
@siddhi-244 @Sulagna-Dutta-Roy Please check it now.

**Comment by Sulagna-Dutta-Roy** [comment]
LGTM !!! 👍

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
@siddhi-244 please approve it

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
