### PR TITLE
Color Picker 

### PR DESCRIPTION
**Pull request by anshulsoni4**
The issue number is - #30 
I have added the color picker project and made this using HTML, Bootstrap 5, and some javascript. also used some font awesome for icons and stuff

- [x]  I have made this on my own
- [x]  I have taken help from some online resources
- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x]  I have made corresponding changes to the documentation
- [x]  My changes generate no new warning
 
 
screenshot of web page

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please follow the PR template and tick all the relevant checkboxes.

**Review by anshulsoni4 — COMMENTED** [review]
pls check the updated PR

**Comment by Sulagna-Dutta-Roy** [comment]
There is only one file showing. @anshulsoni4

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
I can't see any files

**Comment by anshulsoni4** [comment]
how ??

**Pull request closed without merging**
