### PR TITLE
Wordle Game

### PR DESCRIPTION
**Pull request by Shaba1406**
# Description
- This project is about wordle game
- The GUI has been developed using HTML,CSS,Javascript
- Through this we can play a game according to our choice by selecting the beginner,intermediate,hard levels

Fixes: #10 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
| Screenshot #1 |
| ----------- |
| Output |
|Wordled - A Wordle based game - Google Chrome 06-09-2022 20_13_01|
| Screenshot #2 |
| Output |
|Wordled - A Wordle based game - Google Chrome 06-09-2022 20_13_44|

### CODE REVIEW

**Comment by Shaba1406** [comment]
@Sulagna-Dutta-Roy @siddhi-244 @072arushi  Kindly check my PR

**Review by 072arushi — APPROVED** [review]
I really liked your project! Keep it up!!

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Just remove settings.json file

**Comment by Shaba1406** [comment]
> Just remove settings.json file

@siddhi-244 Done with the changes

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
