### PR TITLE
Drum kit

### PR DESCRIPTION
**Pull request by Harsh3363**
# Description

I have made a drum-kit web Application which when clicked on or when the corresponding keys are pressed will play the relevant sound.

Fixes:  #33 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

drum-kit

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please delete the empty files

**Comment by Harsh3363** [comment]
> Please delete the empty files

Done

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
You have added Simon game too. Please see to it

**Comment by Harsh3363** [comment]
> You have added Simon game too. Please see to it

I don't know  but I'm not able to make changes to it I will make a new PR for it after making the changes

**Comment by Harsh3363** [comment]
> You have added Simon game too. Please see to it

done

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add detailed description in the readme + screenshots too

**Comment by Harsh3363** [comment]
> Add detailed description in the readme + screenshots too

done

**Comment by Sulagna-Dutta-Roy** [comment]
> > Add detailed description in the readme + screenshots too
> 
> done

**Comment by Sulagna-Dutta-Roy** [comment]
@Harsh3363 there is only one line showing the readme.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Pull request merged**
