### PR TITLE
Weather App for Non Google Service Devices

### PR DESCRIPTION
**Pull request by biratdatta**
# Description

 I have made a weather app for the devices which doesn't run on Google. I have created this weather app on React with the help of OpenWeatherAPI.

Fixes:  #4   (issue no.)

## Type of change

 
- [X ] New feature (non-breaking change which adds functionality)

- [X] This change requires a documentation update

# Checklist:

- [X ] I have made this from my own
 
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
 

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://weather-for-all.vercel.app/

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Why didn't you mentioned the tech stack in the issue no #4 ???? I'm not accepting react projects right now because JavaScript and react couldn't be together right. So I'm not accepting this Projects because it's in React.

**Comment by Sulagna-Dutta-Roy** [comment]
I can't merge this PR because this project made in React. Please make it in Simple JavaScript otherwise I will close it. Also my projects only accepting Js,css,html projects right now. Sorry for the Inconveniences

**Comment by biratdatta** [comment]
> I can't merge this PR because this project made in React. Please make it in Simple JavaScript otherwise I will close it. Also my projects only accepting Js,css,html projects right now. Sorry for the Inconveniences

I guess react is a JS library and we can use it right? Plain Vanilla JS is not user friendly

**Comment by Sulagna-Dutta-Roy** [comment]
Simple JavaScript vs React dependencies are not same right ??? As you worked with React you know how to set the repository right ??? So In my case I'm not accepting Reactjs projects because of the large dependencies.

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
5000 files? Also it's not vanilla js

**Comment by Sulagna-Dutta-Roy** [comment]
@siddhi-244 please handle it 🙂

**Pull request closed without merging**
