### PR TITLE
Candy Museum

### PR DESCRIPTION
**Pull request by tarunbisht-24**
# Description

I have created a landing page in HTML, CSS, Bootstrap, and JS. This project will help beginners in learning these skills and can apply it on any kind of project.

Fixes:  #82 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

preview

### CODE REVIEW

**Comment by tarunbisht-24** [comment]
@siddhi-244 can you pls review it and merge

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Some of the Images not showing here

**Comment by tarunbisht-24** [comment]
@Sulagna-Dutta-Roy I have already pushed all the images related to this in the Candy Museum project it's all working fine from my side also I have rechecked that all the things are visible in the project.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by tarunbisht-24** [comment]
@Sulagna-Dutta-Roy can you pls merge it under the SSoC'22 tag

**Comment by Sulagna-Dutta-Roy** [comment]
> @Sulagna-Dutta-Roy can you pls merge it under the SSoC'22 tag

Siddhi didn't reviewed till now. Please wait for it

**Review by siddhi-244 — APPROVED** [review]
Lgtm

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
