### PR TITLE
Exploratory data analysis using python (spotify dataset)

### PR DESCRIPTION
**Pull request by Labheshm11**
# Exploratory Data analysis (Spotify dataset)

## Description
This is a eda that makes us understand the basic fundamentals in the Spotify dataset

### Technologies
Python-(pandas,numpy,matplotlib,Kaggle(dataset)

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Change pr title. Change file name

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Make a folder, in that add your files. Change the name of your file

**Comment by Labheshm11** [comment]
Ok I will put it in the folder
But which file are you talking about? I'm unable to understand

**Comment by Labheshm11** [comment]
*change the file name

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Add this project into Python Folder. And I can't see the Pull request template here

**Pull request closed without merging**
