### PR TITLE
Slide share to pdf

### PR DESCRIPTION
**Pull request by Avik-creator**
# Description

It is a project which helps us to download PPT's from SlideShare in PDF Form.
Fixes:  #38 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://user-images.githubusercontent.com/77090462/171180488-659687cb-c559-4f0e-9308-1381cca85471.mp4

### CODE REVIEW

**Comment by Avik-creator** [comment]
@siddhi-244 @Sulagna-Dutta-Roy Please check and review it.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
Please change the filename into 'Slideshare.py' .

**Review by siddhi-244 — APPROVED** [review]
Do the changes said by @Sulagna-Dutta-Roy . Rest looks good to me

**Comment by Avik-creator** [comment]
@Sulagna-Dutta-Roy @siddhi-244 Please check it now.

**Pull request merged**
