### PR TITLE
Digital clock

### PR DESCRIPTION
**Pull request by srinjoy-26**
# Description

A digital clock made using html , css and js. It can be run by simply cloning the repo and running the index.html.
Fixes:  #11 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
179282106-f6deba14-cfce-4b48-a888-4a89e01148cd

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
It would be great if you can add screenshot of your working project in readme

**Comment by srinjoy-26** [comment]
> It would be great if you can add screenshot of your working project in readme

done

**Comment by siddhi-244** [comment]
Instead of a look. You can write demo

**Comment by srinjoy-26** [comment]
> Instead of a look. You can write demo

🙂

**Comment by siddhi-244** [comment]
> > Instead of a look. You can write demo
> 
> 🙂

Have you changed it? So that I can approve the pr!

**Comment by srinjoy-26** [comment]
> > > Instead of a look. You can write demo
> > 
> > 
> > 🙂
> 
> Have you changed it? So that I can approve the pr!

Done

**Review by siddhi-244 — APPROVED** [review]
LGTM🥳🥳

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
