### PR TITLE
Added Durga Puja Website

### PR DESCRIPTION
**Pull request by srinjoy-26**
# Description
Added a durga puja based webpage.

Fixes:  #311 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add more info in the readme

**Comment by srinjoy-26** [comment]
> Add more info in the readme

Done

**Review by 072arushi — APPROVED** [review]

**Comment by srinjoy-26** [comment]
@siddhi-244 please approve

**Comment by Sulagna-Dutta-Roy** [comment]
@siddhi-244

**Comment by Sulagna-Dutta-Roy** [comment]
@siddhi-244 please approve

**Pull request merged**
