### PR TITLE
added browser

### PR DESCRIPTION
**Pull request by srinjoy-26**
# Description

A browser in python.

Fixes:  #139 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/91176055/189485458-a2fc7385-c047-4752-9d8a-7ea88207465f.mp4

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please the filename into browser.py

**Comment by Sulagna-Dutta-Roy** [comment]
@siddhi-244 @072arushi please approve it

**Review by siddhi-244 — APPROVED** [review]

**Review by 072arushi — APPROVED** [review]

**Comment by Sulagna-Dutta-Roy** [comment]
@srinjoy-26 kindly do the changes

**Comment by srinjoy-26** [comment]
> @srinjoy-26 kindly do the changes

done

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
