### PR TITLE
I have modified the html and css files of simple registration form 

### PR DESCRIPTION
**Pull request by Anshitseth**
# Description

I have designed a Simple Registration Form using html , css and bootstrap and also used JavaScript . 
I have modified the previous registration form.

Please include a summary of the change and which issue is fixed. Please also include 

Fixes:  #24 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses eg Bootstrap css Library.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image
image
image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please tick all the checkboxes in the PR template those are relevant to the PR.

**Comment by Sulagna-Dutta-Roy** [comment]
@Anshitseth kindly follow the PR template and add readme file in the PR.

**Comment by Anshitseth** [comment]
Done
Please review it.

**Comment by Anshitseth** [comment]
pls merge it 
I have made the changes

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
There is no readme

**Comment by Anshitseth** [comment]
Ok Sorry for making so many errors .
I will make a readme file and will then request you.

**Comment by Anshitseth** [comment]
Sorry for the delay 
I have created the readme file.
I have  followed the PR template.
please merge it now.
if there is anything else i have to do ,please inform me .

**Review by siddhi-244 — APPROVED** [review]

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
