### PR TITLE
Added the Dino game.

### PR DESCRIPTION
**Pull request by surbhi400**
# Description

Fixes:  #79 

## Type of change
1) It has two pages which are connected to each other.
   -> A landing page which has a start game button with instructions to play the game.
   -> The game page where one can play can game.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
Please add readme file here.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
The image is not visible in readme

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Only 1 feature? Add some more features about it. Like what the game does etc.

**Comment by Sulagna-Dutta-Roy** [comment]
Please add Game UI in the Readme.

**Comment by surbhi400** [comment]
> Please add Game UI in the Readme.

The screenshots of both LANDING PAGE and the the GAME PAGE of this game are already provided in the readme.

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
