### PR TITLE
Improved the UI of Weight Calculator

### PR DESCRIPTION
**Pull request by Vanshiii203**
# Description
Improved the UI of Weight Calculator and made changes in the JavaScript so it could convert in any of the unit.

Fixes:  #26 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (259)
Screenshot (260)

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Can you add the screenshots in readme ?

**Comment by Vanshiii203** [comment]
@siddhi-244 I have added the screenshots in a readme file. Please review it!

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
The screenshots aren't visible

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Pull request merged**
