### PR TITLE
Feat-274-registrationForm

### PR DESCRIPTION
**Pull request by Rancho2002**
# Description

Registration form are often used to do some events. That's why I have built and attached this code to this repositary.

Fixes:  #(issue no.) #274 

## Type of change
New Feature added

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
This project is not a facebook login I guess. kindly write the appropriate project name

**Comment by Rancho2002** [comment]
But I have not write the project name 'facebook login' where do I need to change? pls tell @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
> But I have not write the project name 'facebook login' where do I need to change? pls tell @Sulagna-Dutta-Roy

your project folder name showing 'Facebook Login'

**Comment by Rancho2002** [comment]
> > But I have not write the project name 'facebook login' where do I need to change? pls tell @Sulagna-Dutta-Roy
> 
> your project folder name showing 'Facebook Login'

image
Please check again or provide screenshot

**Review by 072arushi — APPROVED** [review]

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
please delete the facebook login folder.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Review by siddhi-244 — APPROVED** [review]

**Pull request merged**
