### PR TITLE
Youtube clone

### PR DESCRIPTION
**Pull request by harshit-paneri**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #44 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by harshit-paneri** [comment]
Capture

**Comment by harshit-paneri** [comment]
@Sulagna-Dutta-Roy or @siddhi-244 please review it

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Add readme

**Comment by harshit-paneri** [comment]
> Add readme

I just add a readme file Please review it again.

**Review by Sulagna-Dutta-Roy — CHANGES_REQUESTED** [review]
kindly check other readme formats and add those details.

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Pull request merged**
